name: Debug File Structure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show me the files
        run: |
          echo "=== Root Files ==="
          ls -la
          echo "=== Checking inside folders ==="
          find . -maxdepth 2 -not -path '*/
          .*'       uses: actions/upload-artifact@v4
        with:
          name: Tanzeem-Debug-APK
          path: Tanzeem/app/build/outputs/apk/debug/app-debug.apk
